In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

Creating a tensor

In [ ]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why Random Tensors?

Random tensors re important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.


In [ ]:
# Creatin a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1151, 0.2628, 0.3532, 0.7160],
        [0.5191, 0.6965, 0.3130, 0.5624],
        [0.2555, 0.3473, 0.5681, 0.8933]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor_1 = torch.rand(10,10,10)
random_tensor_1

tensor([[[0.8178, 0.5728, 0.0041, 0.5114, 0.4414, 0.9484, 0.4521, 0.7599,
          0.0638, 0.2765],
         [0.2200, 0.9826, 0.3643, 0.8538, 0.4436, 0.4204, 0.9576, 0.3616,
          0.7555, 0.6752],
         [0.1579, 0.1475, 0.4897, 0.5491, 0.3023, 0.3420, 0.6556, 0.9657,
          0.6217, 0.0275],
         [0.8673, 0.0035, 0.7768, 0.3382, 0.6576, 0.9059, 0.7917, 0.2171,
          0.3329, 0.0054],
         [0.5212, 0.5898, 0.6134, 0.2394, 0.8799, 0.1344, 0.4501, 0.1280,
          0.0519, 0.3262],
         [0.2997, 0.3211, 0.2530, 0.3871, 0.8365, 0.9338, 0.4061, 0.6053,
          0.0817, 0.8457],
         [0.8776, 0.9293, 0.6311, 0.7724, 0.8870, 0.7273, 0.0587, 0.0101,
          0.4489, 0.1507],
         [0.5298, 0.4171, 0.6441, 0.9648, 0.7492, 0.3222, 0.7925, 0.2280,
          0.3755, 0.5195],
         [0.1990, 0.7235, 0.4401, 0.6124, 0.4441, 0.9955, 0.5389, 0.5527,
          0.0735, 0.8382],
         [0.1196, 0.0119, 0.0519, 0.7041, 0.0367, 0.9725, 0.4009, 0.9567,
          0.7627,

In [ ]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3,224,224)) #height, width, color channel(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###zeros and ones

In [ ]:
#create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()

one_to_ten = torch.arange(0,11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

**Note:**Tensor datatype is one of the 3 big errors you'll run into with pyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
int_32__tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.int32)
int_32__tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32__tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device fro a tensor, can use tensor.device

In [ ]:
# create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2846, 0.8191, 0.9985, 0.7421],
        [0.1267, 0.2291, 0.4914, 0.2641],
        [0.5641, 0.7778, 0.7114, 0.2089]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2846, 0.8191, 0.9985, 0.7421],
        [0.1267, 0.2291, 0.4914, 0.2641],
        [0.5641, 0.7778, 0.7114, 0.2089]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors(Tensor Operations)

Tensor operation include:

* Addition
* Subtraction
* Multiplication(Element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#try out puTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multipliaction(dot product)

The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)
* Note: "@" in Python is the symbol for matrix multiplication.

In [ ]:
#Element wise multiplication
print(tensor * tensor)


tensor([1, 4, 9])


In [ ]:
#Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.48 ms, sys: 0 ns, total: 1.48 ms
Wall time: 1.48 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 66 µs, sys: 11 µs, total: 77 µs
Wall time: 80.8 µs


tensor(14)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.3161, 0.1431],
        [1.0686, 0.6034]])

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) is same as torch.matmul()

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A transpose switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Fiding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in the tensor that ahas the minimum value with argmin() -> returns index psition of target tensor where the minimum valur occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position in the tensor that has the mamximum value with argmax() -> returns index position of target tensor where the maximum valur occurs
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqeeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in aa certai  way

In [ ]:
#create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other

x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
# Squeezing
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# Unsqueeze
x_reshaped.unsqueeze(dim=0)

tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [ ]:
# Permute
x_original = torch.rand(size=(224, 224, 3))  # [height, width, color_channel]

x_permuted = x_original.permute(2, 0, 1)  #Shifts axis 0->1, 1->2, 2->0
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all avlues of 0th and 1st dimensions but only index 1 and 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all avlues of 0 dimesion but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st diemnsion and all values of 2nd dimension
x[0][0][:]

tensor([1, 2, 3])

### PyTorch tensors and NumPy

NumPy is a popular scientific python numerical computing library
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducability (trying to take random out of random)

In short how a neural network learns:

' start with random numbers -> tensor operation -> update random numbers to try and make them better representations of the data -> again -> again -> ... '

To reduce the randomness in nueral networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4748, 0.4124, 0.9334, 0.4060],
        [0.1368, 0.1523, 0.8761, 0.3212],
        [0.0108, 0.2409, 0.1848, 0.2921]])
tensor([[0.9359, 0.9137, 0.7449, 0.3160],
        [0.3568, 0.3827, 0.8733, 0.4909],
        [0.8087, 0.8765, 0.4500, 0.5121]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Putting Tensors(and modules) on the GPU

The reason we want our tensors/modules on the GPU is because using a GPU results in faster computations

In [2]:
import torch

# create a tensor(default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
# Move tensor to GPU(if available)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### Moving tensors back to CPU

## Exercise

 1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

2. Create a random tensor with shape (7, 7).

In [2]:
import torch
# create a random tensor

random_tensor_A = torch.rand(7,7)
random_tensor_A

tensor([[0.9616, 0.5372, 0.7345, 0.2636, 0.2378, 0.4809, 0.6661],
        [0.4702, 0.4679, 0.2999, 0.3103, 0.2438, 0.2552, 0.1465],
        [0.8271, 0.2734, 0.7663, 0.6873, 0.5759, 0.3156, 0.5275],
        [0.1799, 0.1022, 0.4894, 0.4212, 0.2071, 0.8787, 0.3365],
        [0.5545, 0.2890, 0.6034, 0.5908, 0.8225, 0.1963, 0.2514],
        [0.0440, 0.2705, 0.7251, 0.7777, 0.2617, 0.9686, 0.4346],
        [0.1555, 0.2177, 0.8385, 0.4077, 0.5856, 0.2854, 0.3247]])

In [3]:
random_tensor_B = torch.rand(1,7)
random_tensor_B

tensor([[0.4493, 0.1084, 0.3860, 0.6832, 0.4852, 0.9262, 0.2528]])

In [5]:
torch.matmul(random_tensor_B, random_tensor_A)

tensor([[1.2743, 0.9132, 2.1691, 1.8152, 1.2866, 2.0305, 1.3553]])

In [8]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(1,7)

print(random_tensor_C)
print(random_tensor_D)

torch.matmul(random_tensor_D, random_tensor_C)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752]])